version: '3.9'

services:
  web:
    build: ./apps
    image: "avihaycognyte/flask-scores:1.1"
    ports:
      - "8777:8777"
    environment:
      FLASK_APP: MainScores.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8777
      FLASK_ENV: development
    volumes:
      - ./apps/Scores.txt:/Scores.txt
