version: '3.9'

services:
  flask-scores-app:
    build: .
    image: "avihaycognyte/flask-scores:1.1"
    ports:
      - "8777:5000"
    volumes:
      - ./Scores.txt:/Scores.txt
    environment:
      FLASK_APP: MainScores.py
